### ISSUE TITLE
django-braces dropped in django-oauth-toolkit 1.0.0

### ISSUE THREAD

**Issue by MarcMacia** [PhilipGarnero/django-rest-framework-social-oauth2#103]
In the CHANGELOG.md of django-oauth-toolkit:
1.0.0 [2017-06-07]
...
The dependency on django-braces has been dropped.
..

You are using django-braces in views.py. You shoud add that dependency in your project to avoid the error.

**Comment by tamayonauta** [comment]
@MarcMacia The pull #98 has solution for this issue.
For now the merge has not been made.

**Comment by PhilipGarnero** [comment]
#98 Was merged and a new version has been released.
Thanks !
