### ISSUE TITLE
How to use with facebook?

### ISSUE THREAD

**Issue by samupl** [PhilipGarnero/django-rest-framework-social-oauth2#104]
Hi! I'm struggling with using your library to authenticate my api calls using facebook.

What I'm aiming for is for my users to pass facebook access_token to my api in order to get authenticated. My api of course needs to know who the user is and store the user in the Users table.

Now I've already seen https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/issues/42 - as I've run into the same error. However, the code the guy suggested there isn't working for me - with just a primitive version of the authentication backend (returning an empty dict), a new User model is created each time I do a request. What might I be missing?

**Comment by PhilipGarnero** [comment]
Normally, simply following the tutorial should get you a working environment.
Could you show me what you've done and the requests you're doing ?
