### ISSUE TITLE
How to specify client key and client secret of multiple facebook and google clients  in settings.py file

### ISSUE THREAD

**Issue by narendra36** [PhilipGarnero/django-rest-framework-social-oauth2#106]
Hi!  Suppose I am building and API which is consumed by an Android app(let's say MyApp) and a web application(let's say MyWeb) and I am using django-rest-framework-social-oauth2 for user login via facebook and google.
Let's suppose we have two users A and B. A logging via MyApp and B logging via MyWeb and MyApp and MyWeb both have different client id and client secret for Facebook or Google then here is problem arises 
How can I specify client key and client secret of both application(MyWeb and myApp) in my settings.py file to allow both applications to use my API? 
SOCIAL_AUTH_FACEBOOK_KEY and SOCIAL_AUTH_FACEBOOK_SECRET are list type or a string variables? How can I specify facbook_key and facebook_secret of both application in settings.py?

**Comment by PhilipGarnero** [comment]
This is an issue with python-social-auth. You should check over there first and come back here if you have a solution you can implement with my package.
