### ISSUE TITLE
I would like to use serializers.HiddenField.

### ISSUE THREAD

**Issue by murabo** [PhilipGarnero/django-rest-framework-social-oauth2#109]
When post method is executed, instead of sending User_id,
`User = serializers.HiddenField(default = serializers.CurrentUserDefault())`
Want to use.
but becomes `AnonymousUser`.

**Comment by PhilipGarnero** [comment]
I'm sorry but I don't understand what you're trying to do.
Also, this seems like a serializing issue, I'm not sure the problems lies within this library.

**Comment by murabo** [comment]
where login user data?

request.user is AnonymousUser

exp)
```
class BookingViewSet(viewsets.ModelViewSet):
    queryset = Booking.objects.filter(is_deleted=False)
    serializer_class =BookingSerializer

    def create(self, request, *args, **kwargs):
        super(BookingViewSet, self).create(request, *args, **kwargs)
        print "User: ", request.user
```

```
User:  AnonymousUser
```

**Comment by PhilipGarnero** [comment]
There can be multiple reasons why your user is anonymous.
The first one I think of is that you didn't authenticate your user properly.
Try putting a login required permission on your viewset and that should prevent you from getting anonymous users.

**Comment by murabo** [comment]
hmmm...

http 401 error
```
{"detail":"{\"error\":{\"message\":\"Invalid OAuth access token.\",\"type\":\"OAuthException\",\"code\":190,\"fbtrace_id\":\"CtU8Ztff1nz\"}}"}(
```

**Comment by PhilipGarnero** [comment]
The error is written in the response.
You're sending an invalid token.

Did you follow the tutorial in the readme ?
Alternatively, someone made a video for the tutorial : https://www.youtube.com/watch?v=kjp8jYJhujA

**Comment by murabo** [comment]
thx

I was reading the tutorial,
Header did not need backend name.

>curl -H "Authorization: Bearer <backend_name> <backend_token>" http://localhost:8000/route/to/your/view
