### ISSUE TITLE
Subclass TokenAuthentication to work

### ISSUE THREAD

**Issue by philliparente** [PhilipGarnero/django-rest-framework-social-oauth2#111]
I had to subclass the TokenAuthentication class to make my view able to work on "Convert token" method (Making only few requests to facebook and using conver-token to work on it), change the field reference "key" to "token" and set the class property "model" to get_access_token_model(), from oauth2_provider.models file. If it's ok, I suggest you to add in the docs! Thanks!

**Python:** 2.7.x
**DRF:**  3.6.x
**Django:** 1.10.x
**Django-oauth-toolkit**: 1.0

```python

from oauth2_provider.models import get_access_token_model
from rest_framework.authentication import TokenAuthentication

...

class BearerTokenAuthentication(TokenAuthentication):
    keyword = u"Bearer"

    def authenticate_credentials(self, key):
        model = get_access_token_model()

        try:
            # here changing model.objects.select_related('user').get(key=key) to 
            # model.objects.select_related('user').get(token=key)
            token = model.objects.select_related('user').get(token=key)
        except model.DoesNotExist:
            raise exceptions.AuthenticationFailed(_('Invalid token.'))

        if not token.user.is_active:
            raise exceptions.AuthenticationFailed(_('User inactive or deleted.'))

        return (token.user, token)
```

**Comment by PhilipGarnero** [comment]
Could you explain your use case ?
What did you change for your view to stop working with the normal flow ?
Why did you have to do that ?

**Comment by philliparente** [comment]
For example, to make the view able to use tha method.
```python
class FooView(viewsets.ReadOnlyModelViewSet):
    queryset = Foo.objects.all()
    serializer_class = FooSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = (IsAuthenticated,)
    authentication_classes = (BearerTokenAuthentication,)
```

**Comment by PhilipGarnero** [comment]
Why didn't you use `oauth2_provider.contrib.rest_framework.OAuth2Authentication` or `rest_framework_social_oauth2.authentication.SocialAuthentication` ?
