### ISSUE TITLE
How to customize the error response ?

### ISSUE THREAD

**Issue by Dineshs91** [PhilipGarnero/django-rest-framework-social-oauth2#114]
Currently, if wrong credentials are given the response is as follows.

```
{
  "error": "invalid_grant",
  "error_description": "Invalid credentials given."
}
```

I want to customize this response to show a different message. Is it possible ?

**Comment by PhilipGarnero** [comment]
The errors are coming directly from [django oauth toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/index.html).
If you want to customize them, you'd have to override my views and reimplement them yourself.
[Here is something you could start looking at](https://django-oauth-toolkit.readthedocs.io/en/latest/views/details.html#oauth2_provider.views.mixins.OAuthLibMixin.error_response).

**Comment by Dineshs91** [comment]
@PhilipGarnero Thanks for the link.
