### ISSUE TITLE
How can I return the user details from convert token view?

### ISSUE THREAD

**Issue by gopalsareen** [PhilipGarnero/django-rest-framework-social-oauth2#115]
I tried to get user from request `request.user`, but it always return AnonymousUser

**Comment by PhilipGarnero** [comment]
This means that your user is not authenticated.
Have you set the permission login_required on your view ?

**Comment by gopalsareen** [comment]
Hi Philip, I guess you misunderstood my question. I have added more details below:

I am trying to  retrieve user details from the convert-token view. My custom view inherits from [ConvertTokenView](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/blob/3313fdeeadd054ca5c7c162cb6b2e9b581cfdb62/rest_framework_social_oauth2/views.py#L50), but when I try to retrieve the user from request, it returns return AnonymousUser.
```
class MyTokenView(ConvertTokenView):

    def post(self, request, *args, **kwargs):

        response = super(MyTokenView, self).post(request, *args, **kwargs)


```

**Comment by PhilipGarnero** [comment]
Retrieving the user here is quite complicated if you want to do it cleanly. You'll need to override around 4 or 5 different classes.

Quick and dirty way :
get the access_token from the response, then use the oauth2_provider.models.AccessToken model to retrieve the user by doing something like `AccessToken.objects.get(token=response.access_token).user`

That should answer to your needs without modifying every class used in django_oauth_toolkit
