### ISSUE TITLE
Unsuccessful in getting this to work

### ISSUE THREAD

**Issue by woodmicha** [PhilipGarnero/django-rest-framework-social-oauth2#119]
Phillip,

I'm quite sure it's **NOT** an issue in your code and sure it's something in my **settings/app** pasted below.

I'm assuming passing an Authorization: Bearer <access-token> is sufficient for this library to authorize GET requests.  The behavior I'm seeing is a 302 being returned even when the token is valid.  I was guessing it would simply return 401 or 403 at which the iOS client would know to authenticate via the OAuth2 party Strava.

For a bit of context my app is a Strava OAuth2 application that's been web only for ~6 months and I'm trying to get a REST api up and running for a iOS app I'm working on.  Given this my hope is the tokens I have created and used for our  2000 users will also be valid for the REST app.

[zippy.txt](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/files/1265950/zippy.txt)

Thanks in advance for any guidance.

Mike

**Comment by woodmicha** [comment]
Got much further today using a clean install that is just the API application and not a mix of both HTML and REST.  One of my issues was I had login_required decorator on class.as_view() in the urls.py for the REST views.   That's what was confusing the curl and iOS calls.

Now I believe I've found a bug in the StravaOAuth implementation.  When using the Authorization: bearer strava <token> it works up until a point within the StravaOAuth class: get_user_details encounters a key error when inspecting response.

Details:

For some reason the response in `oauth.py.do_auth` line 404 is {} while the data on 403 has the correct strava user attributes.  This is the root cause of a key error later on from line 409 when the strategy is executed because the `StravaOAuth.get_user_details` is expecting the attributes to be in an `athlete` node of the response.

This node is filled out fine when I use this OAuth provider with my web app, but empty when I use the rest_framework with your bits.  I can put in a work around but figured I'd ask you if it sounds familiar as something that often needs to be done for REST authentication.

FWIW, the strava bits work fine getting the data and now I understand why new tokens for my app would be better performance.  Not sure why the framework needs to hit strava every time instead of looking locally in the social_auth_usersocialauth table in django DB since the tokens are there too.  Perhaps you can elaborate on that.  FWIW, web apps don't hit strava every time.  They just do it during authorization when the token is created or after you log out on the website or the cookie expires (perhaps this is the reason since we're stateless with no cookies?).

If I do try to improve this by having strive.ai specific tokens I'm hoping I can do that without impacting the web tokens and just have that as step one in the iOS app when registering or something.   I haven't done any app stuff in the Django admin app so I'd need to figure that out but I assume that isn't hard.  As long as it doesn't goof up my existing tokens or users.

LMK your thoughts.

Cheers,

Mike

**Comment by PhilipGarnero** [comment]
I'm sorry but this is an issue with [python-social-auth](https://github.com/python-social-auth/social-core).
Could you reopen your issue there ?

For what I could gather from your post, you may be needing some more configuration on your end (scopes maybe ?) or this could very much be a bug.
