### ISSUE TITLE
[Question] Is it possible to make user lose access if social account is deleted?

### ISSUE THREAD

**Issue by felipejfc** [PhilipGarnero/django-rest-framework-social-oauth2#121]
Hi,

I want to use google auth to permit users from our company domain in one django app of ours, my question is: do this plugin works in a way that if an user email has been deleted it will lose access to the app? If so, what's the needed config?

Regards

**Comment by PhilipGarnero** [comment]
If your users account has been deleted, they won't be able to login using google anymore.
However, they may have access token and refresh tokens they can still use.
You can simply revoke all of your user's tokens and he won't be able to login anymore.
