### ISSUE TITLE
Facebook Account kit access token conversion giving error

### ISSUE THREAD

**Issue by randomdude3512** [PhilipGarnero/django-rest-framework-social-oauth2#123]
I was using facebook account kit to authenticate the user.
1. I used facebook account kit and upon sms verification I get a code..
2. Then I used facebook graph api to get the access token for facebook using the code..
Used the python version of [php implementation of server side](https://developers.facebook.com/docs/accountkit/webjs#examplephp)
3. Now when I want to convert the token I got from step 2, it's giving the following error.
Any help ? 
```
{
    "error": "invalid_request",
    "error_description": "Backend responded with HTTP400: {\"error\":{\"message\":\"Malformed access token\",\"type\":\"OAuthException\",\"code\":190,\"fbtrace_id\":\"Dqj9NS+xwX9\"}}."
}
```

**Comment by jscheller** [comment]
I was getting a similar error in a different scenario, and what I ultimately figured out was that I trying to pass as oauth code (not an access token) to convert_token. I'm using Vue.js and vue-authenticate to build an client-side app that calls through Django and DRFS. It kicked up the same "malformed access token" error when I got the initial response and handed to Facebook via DRFS.

You need to ask Facebook to convert the code into an access code by making a request through
https://graph.facebook.com/oauth/access_token to make the code->access_token conversion happen...

https://stackoverflow.com/questions/11130528/malformed-facebook-access-token

You may also find this DRFS issue useful reading...

https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/issues/72

I'm still personally trying to figure out how to make this code->access_token thing happen while integrating this angry mob of javascript components happy. It sure seems like this would be the key part of the backend library unless I'm missing something, but it appears other folks have struggled down the same path and implemented their own server-side solution for doing the conversion. [erik_sn](https://github.com/erik-sn) posts a link to one he did for a github backend in that issue above and I'm looking at having to write similar ones for facebook and twitter tomorrow unless something else pops into my head while I'm sleeping tonight.

**Comment by PhilipGarnero** [comment]
Thanks @jscheller for your help.

Closing this because related to #72
