### ISSUE TITLE
Question: Return JWT for user instead of tokens

### ISSUE THREAD

**Issue by kinesii** [PhilipGarnero/django-rest-framework-social-oauth2#124]
How would I go about returning a JWT instead of a token to my frontend?

I can manually create a JWT like so (with the rest_framework_jwt module):

```
from rest_framework_jwt.settings import api_settings
jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER


def manual_create_JWT(user):
    """ Generate JWT token for user and pass back to client. Requires the user to be authenticated.  """
    payload = jwt_payload_handler(user)
    return jwt_encode_handler(payload)
```

**Comment by PhilipGarnero** [comment]
We use django-oauth-toolkit as our token generator.
You should check over [there](https://github.com/evonove/django-oauth-toolkit/search?q=jwt&type=Issues&utf8=%E2%9C%93) the progress on token customizations.
