### ISSUE TITLE
IntegrityError at /auth/convert-token/

### ISSUE THREAD

**Issue by Utkarsh3587** [PhilipGarnero/django-rest-framework-social-oauth2#126]
I am trying to use `convert-token` api and it  throws integrity error. .
Detailed Error is:
```
IntegrityError at /auth/convert-token/
duplicate key value violates unique constraint "authentication_user_email_key"
DETAIL:  Key (email)=(abcd@gmail.com) already exists.


Request Method: POST
Request URL: http://localhost:8000/auth/convert-token/
```
Reason: 
First, I converted a token using Facebook as backend  with email id `abcd@gmail.com` and when I am trying to convert token for `abcd@gmail.com` using GoogleOAuth2 as backend, it gives me Integrity Error. Email is Required field in my model.
I am still learning django and trying to figure this out. Can you suggest a way to solve this issue?

Thanks for your library.

**Comment by PhilipGarnero** [comment]
You should look into the [pipeline from python-social-auth](http://python-social-auth.readthedocs.io/en/latest/pipeline.html#authentication-pipeline).
I think activating `'social_core.pipeline.social_auth.associate_by_email',` should be enough for your problem.
