### ISSUE TITLE
How to associate uset with access token

### ISSUE THREAD

**Issue by X17** [PhilipGarnero/django-rest-framework-social-oauth2#13]
i have login with g+ and facebook both in my app. I have this specific case which requires mandatory facebookdata, if an user is logged in from G+ i need to associate user with facebook profile using access_token not with email as i only require association and to avoid new user creation and access token again.

**Comment by PhilipGarnero** [comment]
You would need to implement that in social auth pipeline or implement a custom backend for this.
Check the docs [here](http://psa.matiasaguirre.net/docs/pipeline.html#authentication-pipeline).

As this is not really related to this project, I'll close this issue.
If however you weren't able to succeed only with social auth feel free to reopen.
