### ISSUE TITLE
Problem with Python 3.6.4

### ISSUE THREAD

**Issue by tximpa91** [PhilipGarnero/django-rest-framework-social-oauth2#133]
'DEFAULT_AUTHENTICATION_CLASSES'. ModuleNotFoundError: No module named 'django.core.urlresolvers'.

This error always

**Comment by tximpa91** [comment]
i change the authentication.py from "from 'django.core.urlresolvers import reverse " to "from django.urls import reverse" i Think the Problem is with Django 2.0 that 'django.core.urlresolvers is deprecated

**Comment by Andruten** [comment]
Yes, this is related to #132.
