### ISSUE TITLE
No module django.core.urlresolvers (Django 2.0)

### ISSUE THREAD

**Issue by pazikkamil** [PhilipGarnero/django-rest-framework-social-oauth2#134]
Spotted problem with 
**django.core.urlresolvers** in Django 2.0 it should be **django.urls** - they moved method in this place
![image](https://user-images.githubusercontent.com/12029201/34645981-9709562a-f35c-11e7-9abd-0d8cd6af742e.png)

**Comment by pazikkamil** [comment]
seams to be problem just with package fro pypi - is there just old version still ?

**Comment by baneizalfe** [comment]
Django 2.0 removes the django.core.urlresolvers module, which was moved to django.urlsin version 1.10. You should change any import to use django.urls instead

**Comment by gogson** [comment]
+1

**Comment by pazikkamil** [comment]
yep. Sure its a problem but I guess new package shoul be generated for pypi

**Comment by mihaipopescu0409** [comment]
+1

**Comment by xCEZAREx** [comment]
Needs updated package at pypi. Its not so good for hand updating files after deploying.

**Comment by Andruten** [comment]
+1

**Comment by lvieirajr** [comment]
+1 Can we make a new release with the updates to work with Django 2.0?

**Comment by leogoncalves** [comment]
If you really need to use the updated package to do some testing, try cloning this repository. Not the recommended, but until it is upgraded in the pip is an option. In this [link](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch) you have some options on how to do it.

**Comment by PhilipGarnero** [comment]
Sorry about the wait everyone.
Version 1.1.0 supporting django 2 is published on pypi
