### ISSUE TITLE
Running the facebook tutorial and getting "Invalid client_id parameter value."

### ISSUE THREAD

**Issue by dsrizvi** [PhilipGarnero/django-rest-framework-social-oauth2#14]
I'm putting in the right client id and secret after following the fb example on the page and I keep getting 
"{"error_description": "Invalid client_id parameter value.", "error": "invalid_request"}. 

Any ideas?

**Comment by PhilipGarnero** [comment]
I would need the application's model data as well as the request you made to help you

**Comment by dsrizvi** [comment]
Request I made is the one in the tutorial and I haven't setup any models yet; just trying to get the authentication working.

**Comment by PhilipGarnero** [comment]
You need to create an application to try the authentication system, it is stated in the tutorial. If there is something you don't understand feel free to ask but you might want to reread the tutorial first.

**Comment by dsrizvi** [comment]
Sorry! I just started learning django and I read the tutorial wrong.

**Comment by puneetagg** [comment]
@PhilipGarnero I am not able to understand the reason for creating an application in authentication system for even using social logins like Facebook. Can you please elaborate?

**Comment by PhilipGarnero** [comment]
You need to create an application for your own oauth2 workflow.
All your in-house tokens will be linked to it.
Without an application, you could still use the authentication classes but you wouldn't be able to convert your tokens.
Converting your tokens is quite important because it allows you to avoid contacting facebook at each request to know if the current user exists.

**Comment by puneetagg** [comment]
I have few doubts on this:
1. So, my normal logins will also be based on oauth2 workflow? If yes, I have implemented the same using djanfo-rest-framework-jwt already and now will I have to change that?
2. What if user goes to Facebook and revokes the access for the app, he will still be able to use that until he logins again?

**Comment by PhilipGarnero** [comment]
1. Yes, the goal is to have only one very simple auth backend to use. You can drop jwt or try do use my framework along it but it won't be very simple and straightforward.
2. The facebook part only acts as a way to get user credentials. Facebook won't be used after this anymore except if you lose the token and the refresh token. If the user revoke the facebook permissions and you still have the tokens, he will still be able to log on your app. If you don't have the tokens, the permissions will be asked again.

**Comment by puneetagg** [comment]
Can we chat as I have some questions in context of authentication?

**Comment by PhilipGarnero** [comment]
I'm sorry but I don't really have the time to have a direct exchange with every user.
You can send me an email with all your questions and I will try to answer you when I have time.

**Comment by smentek** [comment]
Fair enough. But I wonder if it is really not possible to set up some better error reporting for that case...

**Comment by nyabwana** [comment]
I have followed every step of the tutorial but I keep getting this error {"error_description":"Invalid client_id parameter value.","error":"invalid_request"} when I try to convert the token from facebook. Is there anything I am missing out on?

**Comment by bertdawg76** [comment]
I am getting this error {"error":"invalid_request","error_description":"Invalid client_id parameter value."}.  I am using my App id for client id(there is no client id on facebook developer site, just an app id) and App secret for client secret.  I use this app id to get a token from facebook, and that works fine, but when i try to submit it using curl, i get the previous mentioned error.

**Comment by KiyoKando** [comment]
To whom stuck here, Is your facebook developer's app valid?
Your app would be expired in 6 month, try remake it.

And, make sure that your client id should be the one in the local Django app.
Not one in the facebook dev site.
