### ISSUE TITLE
Where should Client ID and Client Secret be stored?

### ISSUE THREAD

**Issue by nikhilponnuru** [PhilipGarnero/django-rest-framework-social-oauth2#141]
Hi
I get facebook access token from the react-native implemented android app ( using facebook-login sdk).
I have created application as mentioned in readme and have tested successfully everything using curl.

Now my doubt is how to send client-id and client-secret generated from creating application to 'convert-token' endpoint?.
from my app I send my access token but to convert it I need to call convert-token using client id and secret, how to do it? should I send client id and client secret too from my app along with fb access token?

**Comment by PhilipGarnero** [comment]
In the admin, set client type to `public` in the Application model.
You should then be able to only provide the client id and therefore, not needing to send the client secret anymore
