### ISSUE TITLE
Custom field returned from TokenView

### ISSUE THREAD

**Issue by igorbpf** [PhilipGarnero/django-rest-framework-social-oauth2#142]
Sorry! I'm not sure if this is the right place for questions, but I've just started using this module in a legacy project. Everything is running well, but I need to return a property of my user model in the response of my login view. Does anyone know how to do that?

This is my view:

`class LoginView(TokenView):

    serializer_class = TokenSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        for key in serializer.data:
            request.data[key] = serializer.data[key]
        return super().post(request, *args, **kwargs)
`

and this is my serializer:

`class TokenSerializer(BaseTokenSerializer):

    email = serializers.CharField(required=True)
    password = serializers.CharField(required=True)
    username = serializers.SerializerMethodField()

    def get_username(self, obj):
        return obj['email']

    def validate_grant_type(self, value):
        if value != 'password':
            raise serializers.ValidationError('Unsupported grant_type.')
        return value
`

**Comment by PhilipGarnero** [comment]
Instead of trying to change the Serializer, try changing only the response of the view.
Some tips here : #115
