### ISSUE TITLE
Google Whitelisted Domains

### ISSUE THREAD

**Issue by paulpoot** [PhilipGarnero/django-rest-framework-social-oauth2#143]
Hello, I'm currently working on an intranet for a company that uses G Suite for their email addresses. This means that every employee (and thus everyone that needs access to the system) has an @companyname.com email address. Previously I set the following social auth variable to restrict access:

`SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['companyname.com']
`
However, this does not seem to work in combination with this module. I've got a Vue.js progressive webapp that uses hello.js to login to Google on the client side, then either including the access_token in the Authorization header directly or first exchanging it for a token for my app results in access for the protected resource.

Any thoughts on this? I'm not sure if this is something that isn't currently supported, or that this is an issue with the flow I implemented (the Google login happening client-side, that is).

**Comment by PhilipGarnero** [comment]
You'll have to ask directly to python social auth.
My project is simply a proxy to their library

**Comment by mayankwadhwani** [comment]
@paulpoot  were you able to figure it out?
I tried with gmail.com as domain and it worked for me.
