### ISSUE TITLE
Callback function. 

### ISSUE THREAD

**Issue by IamPsi** [PhilipGarnero/django-rest-framework-social-oauth2#17]
I want to design call back functions for my app using django-rest-framework-social-oauth2 is it possible to do so? If yes, then how? I tried finding it out in the documentation did not get anything on it.

**Comment by PhilipGarnero** [comment]
Callback functions ?
What do you need to do ?
Where, when, and how would you like to do it ?

**Comment by IamPsi** [comment]
Basically I would like to fetch some data of the user from the back end if
the user is logging again(as in after he uses my app again after logging in
for the first time.) Thanks for such a prompt reply.

**Comment by PhilipGarnero** [comment]
Well, you could do that using the [pipeline](http://psa.matiasaguirre.net/docs/pipeline.html) from python-social-auth !
It's pretty simple and flexible enough to allow you to define complex behaviors.
