### ISSUE TITLE
How to increase the expires_in timeout?

### ISSUE THREAD

**Issue by fabiovasini** [PhilipGarnero/django-rest-framework-social-oauth2#176]
Hello,
When a new token is created, the timeout window is very small.
Is there a way configure the app for a longer timeout?

**Comment by biosini** [comment]
Hi Philip,
Thanks for your reply.
I set up ACCESS_TOKEN_EXPIRE_SECONDS in settings, but I'm still getting `"expires_in":36000` with the response.

**Comment by biosini** [comment]
I forgot to update this question..
Anyway, the right way to change the expiration for the access token is:
```
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 604800
}
```
This way django-oauth-toolkit will update the default settings.
