### ISSUE TITLE
Error in README.rst

### ISSUE THREAD

**Issue by YeisonVargas** [PhilipGarnero/django-rest-framework-social-oauth2#18]
@PhilipGarnero Thank for this great library! In this [section](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2#social-authentication), there is a error:

`curl -H "Authorization: Bearer` ~~<backend_name~~~~>~~ `<backend_token>" http://localhost:8000/route/to/your/view` 

it shouldn't put <backend_name> in this request.

Again, Thank so much for this great library!

**Comment by PhilipGarnero** [comment]
Actually, this is not an error, I use this backend_name in my SocialAuthentication class to find which backend the token is linked to. This class is used whenever you want to authenticate someone without having to implement the oauth2 side with inhouse tokens.
For example, if you wanted to authenticate a facebook user, you should put `Bearer facebook access_token`.
You probably put an oauth2 inhouse token that is why you didn't need to specify the backend.
