### ISSUE TITLE
Send data for Python Social Auth

### ISSUE THREAD

**Issue by YeisonVargas** [PhilipGarnero/django-rest-framework-social-oauth2#19]
Hello @PhilipGarnero thank for clarify me in the other issue. I use FIELDS_STORED_IN_SESSION in Python Social Auth, can I send this data for Python Social Auth when django-rest-framework-social-oauth2 library creates a new user using Python Social Auth?

**Comment by PhilipGarnero** [comment]
Well, as django-rest-framework-social-oauth2  is designed for apis I don't see how you would use sessions in this case. But I think you could emulate your behavior by making two calls on the api using [partial pipelines](http://psa.matiasaguirre.net/docs/pipeline.html#partial-pipeline) maybe ?
You could also try to retrieve your query params using the `strategy.request` object but I can't guarantee this will work as I didn't try that.

**Comment by YeisonVargas** [comment]
@PhilipGarnero Great! It's working! 

In pipeline I got the variable using: `backend.strategy.request_data()`

Thanks you!
