### ISSUE TITLE
Expired tokens

### ISSUE THREAD

**Issue by hugocore** [PhilipGarnero/django-rest-framework-social-oauth2#2]
Hi @PhilipGarnero!

Question: When we use the 'convert-token' view with a local token which is expired and a third party token that is still valid, the reply is an access token with a negative expire time. Should we check for this case in the IF statement and create and return new token automatically instead of replying with the old one with a negative time and wait for a following new refresh token request?

Return example of the 'convert-token' view: {"access_token":"bf463UvVNwOehbmt2xv4vCMGVbdy3R","token_type":"Bearer","expires_in":-476339,"refresh_token":"MV1wgHB6XKqfEmPDmtoHye4eN0fJvi","scope":"read write"}

With this response, my following action in my application would be to check the "expires_in" field and check if is still positive. Otherwise, the app must send a new request to refresh this token.

**Comment by PhilipGarnero** [comment]
You're totally right.
I've fixed this and now a new token is created when it is expired or  is going to expire in the next minute.
Thanks for your contributions :+1:

**Comment by tezro** [comment]
A bit late, but I got to the same problem. What's the correct way to deal with it guys? So I have a Facebook user with correct token and an expired DRF token. So obviously any requests to an PI returns:
```
{"detail":"Invalid token."}
```
What should I do with expired tokens?

**Comment by PhilipGarnero** [comment]
@tezro You can refresh your token using the refresh token you got at the same time as the access token. Checkout the readme, there is an example about it there.

**Comment by tezro** [comment]
@PhilipGarnero thanks for man, I missed that somehow. One small question, forgive me if I'm understanding it completely. How do I use the client_id and client_secret from the app that is added in Django? For example, we're doing an iOS app and of course can hardcode it and use for the time of development, and use it for requests. But what's gonna happen when we go live? Should I create the application on the production environment with the same values? Or if I'm making say Angular or any other SPA and need to refresh the token, where and how do I get the client_id and client_secret from? I can't just store them in cookies or append to all the urls or something? :)

Or I am completely off the track here and this is perfectly ok?

**Comment by PhilipGarnero** [comment]
No, you are totally right about client id and client secret.
You can hard code it somewhere in your app, even though someone can find it by reverse engineering, they will not be able to do anything else than password grants with it so this is not a critical point.
However, you should **ONLY DO THIS WITH resource owner password-based**.
For other type of public applications, you must never put the client_secret hardcoded somewhere accessible by an user.
For a JS application you could use the implicit grant type for example.
