### ISSUE TITLE
Problem with PROPRIETARY BACKEND (e.g. Django) and reverse('token')

### ISSUE THREAD

**Issue by vfdev-5** [PhilipGarnero/django-rest-framework-social-oauth2#21]
At first thanks for your django application! It is very useful for in my projects!

I want to issue an access_token for an ordinary user (not from social network) and I try to use Django OAuth Toolkit part of your application. I create an OAuth application in my project.
Then I go to the URL:
```
/auth/login/Django/
```
(my PROPRIETARY_BACKEND_NAME is the default one) then there is a redirection to the url : 
```
/accounts/login/?next=/auth/authorize%3Fstate...
```
I login with user's credentials and there is a redirection to a page to authorize the OAuth application
```
/auth/authorize?state=...
```
After the authorization I get a python error on the url (http://127.0.0.1:8000/auth/complete/MyOAuth2/?redirect_state=...)
```
MissingSchema at /auth/complete/Django/
Invalid URL '/auth/token': No schema supplied. Perhaps you meant http:///auth/token?
```
This problem as I understand is related with the code in the [backends.py](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/blob/master/rest_framework_social_oauth2/backends.py) file
ACCESS_TOKEN_URL = reverse('token')

If I create my own backend similar to your DjangoOAuth2 and fix this argument as 
ACCESS_TOKEN_URL = 'http://127.0.0.1:8000/auth/token'

I get another error : 
```
HTTPError at /auth/complete/MyOAuth2/
405 Client Error: METHOD NOT ALLOWED
```
Could you, please, hint how to solve this problem ? 
Cheers

**Comment by PhilipGarnero** [comment]
Are you simply willing to get an access token ?
If that is the case, all you need to do is set up an application with `client_type` set to `confidential` and 
`authorization_grant_type` set to `Resource owner password-based`. Then you would need to use the token route to retrieve your token. All of this is detailed in the readme.
I haven't experimented a lot with the custom social backend as its usage is very specific and I still don't see clearly why would someone use it for the moment.
Try following the readme and everything should go well.
Close the issue when you managed to achieve what you wanted to do.
If this doesn't answer your question please provide more details on what you're trying to do.

**Comment by vfdev-5** [comment]
Yes, you are right about how to issue a token in this schema using user credentials and confidental client type. Sorry, I did not precised that in my case the OAuth application is of type Authorization Code and Public. The use case is when your OAuth server is used by a 3rd-party client...
Actually, I've figured out how to solve my problem, so I can close the issue.
