### ISSUE TITLE
Facebook email not added on user

### ISSUE THREAD

**Issue by baneizalfe** [PhilipGarnero/django-rest-framework-social-oauth2#25]
After fb login which allowed email scope, user is created in django without email from facebook.

**Comment by baneizalfe** [comment]
Starte redaing about social aut pipeline

**Comment by baneizalfe** [comment]
I tried adding 
```
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)
```

But still, user is created instead of associated with email

**Comment by baneizalfe** [comment]
It turns out my custom auth backend which ws put as last was breaking. When put before rest and social auths it worked.

**Comment by krdeepak** [comment]
Currently my authentication backend has the following. 
AUTHENTICATION_BACKENDS = (
    'social.backends.facebook.FacebookAppOAuth2',
    'social.backends.facebook.FacebookOAuth2',
    'rest_framework_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

Same problem, facebook email is not added to User table. Do I need to change the order?
