### ISSUE TITLE
Missing access_token in extra_data

### ISSUE THREAD

**Issue by oudeismetis** [PhilipGarnero/django-rest-framework-social-oauth2#27]
The `user social auths` model created by `python-social-auth` has a json blog called `extra_data`. It contains info like the `username` and `access_token` from the provider.
I'm using the github backend and previously had my own endpoint to authenticate the user myself and take action when provided an access token from github. In that scenario, `extra_data` would contain the `access_token` which could be used for making API calls to github from the backend.

I have now switched to django-rest-framework-social-oauth2 and have noticed that the `access_token` is now null. `id` and `login` are still there and correct.

**Comment by oudeismetis** [comment]
I have a workaround for this issue which I'll detail below. I'm new to these libraries, so I'm having trouble figuring where the proper fix location would be. If anyone has an idea, let me know, I'm more than willing to fork, fix, test, and PR.

My current fix:
Inject a step into python-social-auth:
```
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'path.to.your.view.save_oauth',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)
```
As this step occurs after associate_user, we have the newly created user model as well as the token available to us in the request.
```
@partial
def save_oauth(strategy, details, user=False, *args, **kwargs):
    request = kwargs.get('request', None)
    if user and request:
        access_token = request.get('token', None)
        social = user.social_auth.get(provider='github')
        social.extra_data['access_token'] = access_token
        social.save()
        return { 'is_new': False, 'user': user }
    return { 'is_new': True, 'user': None }
```

**Comment by PhilipGarnero** [comment]
This is not an issue actually. It comes from python-social-auth. Every backend has a different behavior and the user must modify the pipeline according to his needs. This is the expected behavior and this is exactly what you are doing :)

**Comment by oudeismetis** [comment]
The thing is....this wasn't a problem before. I was already using python-social-auth and it was saving the token on the user just fine. 

It was only when I started using django-rest-framework-social-oauth2 that I had to manually set it as above.

**Comment by PhilipGarnero** [comment]
Well, I don't have time to investigate this as this is not blocking but if you find where this comes from tell me and I'll fix it.
You can begin [here](https://github.com/omab/python-social-auth/blob/aa66b83d4848c09defa57384529eca83597a3692/social/pipeline/social_auth.py#L86) and follow [here](https://github.com/omab/python-social-auth/blob/master/social/backends/oauth.py#L44). See if the access token is present, if not track the starting point.

**Comment by oudeismetis** [comment]
Thats fine. Thanks for pointing me in the right direction. If I figure out the root of it, I'll open a PR with whichever project needs the fix.
At least for now there is relatively straightforward workaround.

**Comment by oudeismetis** [comment]
I've confirmed that this is an issue with python-social-auth. Given that it used to work for me, I assume it has to do with version number changes I made when I started using django-rest-framework-social-oauth2. Will continue to investigate and may open an issue with python-social-auth.

This ticket should be closed as far as I'm concerned.

**Comment by PhilipGarnero** [comment]
Thank you for your investigations.
