### ISSUE TITLE
API endpoints not being auto-detected by django-rest-swagger

### ISSUE THREAD

**Issue by oudeismetis** [PhilipGarnero/django-rest-framework-social-oauth2#28]
Not sure how much of a bug this is, but I thought it was worth mentioning as there may be other implications to this issue.

I noticed that django-rest-swagger wasn't finding most of the API endpoints added by django-rest-framework-social-oauth2. 

I believe the below change would fix this. I have not tested fully, but if this fix is considered relevant, let me know and I'll confirm that it works and will open a PR for it.

views.py line:21 ConvertTokenView
Currently extending `django.views.generic.View`. As a result, this isn't a django-rest-framework view and thus doesn't have the attributes that other tools similar to django-rest-swagger look for. Changing this to extend from `rest_framework.views.APIView` should fix this. 

I extended `ConvertTokenView` in my code to make this change. It did fix it, but I ran into an issue with permissions though. That requires adding `permission_classes = (AllowAny,)` as this is an endpoint that should have security on it. 

This fix would need to be made for every endpoint, with the exception of `invalidate_sessions`.

Again, let me know if this is something you want in the project and I'll go down the path of PR'ing.

**Comment by PhilipGarnero** [comment]
Well, this seems appropriate !
I'm waiting for your PR

**Comment by oudeismetis** [comment]
I forked and have been testing. Will try to have a PR before 2016 :smile:
