### ISSUE TITLE
How can I enable two or more back-end names in settings?

### ISSUE THREAD

**Issue by YeisonVargas** [PhilipGarnero/django-rest-framework-social-oauth2#37]
I need to set the PROPRIETARY_BACKEND_NAME with Google and Facebook for allow social authentications with multiple providers.

Is it possible?

Thank for this great library!

**Comment by PhilipGarnero** [comment]
You don't need to set `PROPRIETARY_BACKEND_NAME` for this. Its purpose is to create your own backend.

All you need to do is enabling the backends you want to support.
For this, you have to add the backend to `AUTHENTICATION_BACKENDS` and follow the documentation of your backend you can find in the [python-social-auth documentation](http://psa.matiasaguirre.net/docs/backends/index.html).

It is possible that the implementation of a backend requires you to put more complex informations during the convert-token request. You can see an [example with twitter](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/issues/15). 

If you have anymore questions, feel free to reopen and ask.
