### ISSUE TITLE
'QueryDict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Mrostgaard** [PhilipGarnero/django-rest-framework-social-oauth2#38]
When i run: 
'curl -X POST -d "grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=facebook&token=<facebook_token>" http://localhost:8000/auth/convert-token'

I get this error:
AttributeError at /auth/convert-token
'QueryDict' object has no attribute 'iteritems'

So i went into '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/rest_framework_social_oauth2/views.py' on line 38 and changes the line to: 
'for key, value in request.data.items():'
instead of:
'for key, value in request.data.iteritems():'

I don't know how to create a pull request but the reason was that python 3 uses .items() instead of .iteritems()

**Comment by PhilipGarnero** [comment]
Oh well, that was introduced in the last version. I'll fix this as soon as I have time. Thank you
