### ISSUE TITLE
Get user profile with the token response

### ISSUE THREAD

**Issue by Calzzetta** [PhilipGarnero/django-rest-framework-social-oauth2#44]
Hi,

How could I add the user profile in the response from "auth/convert-token"?

I am performing the social login with Google+. "auth/convert-token" returns only:
`{"expires_in":36000,"refresh_token":"z0y9RzwGMRat4MG28zNBMaNTCIxnjY","scope":"read write","access_token":"SFQQ3RyqiMLIgVR8l5xMzs7pmkHv1b","token_type":"Bearer"}`

In the request header I have:
`Authorization: Bearer SFQQ3RyqiMLIgVR8l5xMzs7pmkHv1b`
But in the view, the request.user is "AnonymousUser".

Best regards,
Douglas

**Comment by PhilipGarnero** [comment]
Please, see #31.
If that does not solve it for you, feel free to reopen and give some more details about what you're trying to achieve.

**Comment by Calzzetta** [comment]
Thank you @PhilipGarnero
