### ISSUE TITLE
Email not added to new user after logging with Facebook

### ISSUE THREAD

**Issue by ArnaudRenaud** [PhilipGarnero/django-rest-framework-social-oauth2#47]
The `settings.py` file contains:
`SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']`

1. I log in to Facebook with a user that doesn't exist in the `User` table of my Django app.
2. I try to login server-side after having exchanged the frontend user access token with a backend token: `curl -H "Authorization: Bearer facebook <backend_token>" http://localhost:8000/auth/login/facebook/`

Result:
The new user has been properly created in the table but `<user>.email` is set to `''`.

I also tried to add `'social.pipeline.social_auth.associate_by_email'` to `SOCIAL_AUTH_PIPELINE` but the behavior didn't change.

**Comment by PhilipGarnero** [comment]
Apparently, facebook changed its API and python-social-auth does not seem really up to date with the changes.
See https://github.com/omab/python-social-auth/issues/675
