### ISSUE TITLE
Link between backend token and user?

### ISSUE THREAD

**Issue by ArnaudRenaud** [PhilipGarnero/django-rest-framework-social-oauth2#48]
After converting the third-party access token into a backend token (`/convert/token/`) and logging in to the app with the backend token (`/login/`), where is the link between the user and the token?

`rest_framework.authtoken.models.Token.objects.all()` returns an empty list even though `'rest_framework.authtoken'` is in `INSTALLED_APPS` and the table has been migrated.

**Comment by PhilipGarnero** [comment]
It isn't a rest framework token but a oauth2_provider AccessToken.

**Comment by ArnaudRenaud** [comment]
I fail to understand if there is any built-in way to return a token or a session ID to the client after having logged in.

**Comment by PhilipGarnero** [comment]
I don't understand what you're trying to do here.
If you're meaning receiving the token for the first time, it is covered in the readme.
> curl -X POST -d "client_id=<client_id>&client_secret=<client_secret>&grant_type=password&username=<user_name>&password=<password>" http://localhost:8000/auth/token
 
If that is unclear for you, I suggest you read a bit more on [the oauth2 process](https://aaronparecki.com/2012/07/29/2/oauth2-simplified).

**Comment by ArnaudRenaud** [comment]
I already have an access token (got it from the conversion of the third-party token).
I'm now trying to link the access token to the matching user in the User table (`django.contrib.auth.models`).

I'm referring to this excerpt from the readme:
`You should use this token on each and further communications between your system/application and your api to authenticate each request and avoid authenticating with FB every time`.

**Comment by PhilipGarnero** [comment]
Simply use the authentication classes provided and the user will be automatically loaded in request.user

**Comment by ArnaudRenaud** [comment]
Thank you, that worked with the authentication class `from oauth2_provider.ext.rest_framework import OAuth2Authentication`.
