### ISSUE TITLE
Generate AccessToken server side

### ISSUE THREAD

**Issue by andrroy** [PhilipGarnero/django-rest-framework-social-oauth2#51]
Hi,

I have created an endpoint in my application for user registration. The way I want my endpoint to work, is that a user is created (username, email and password), the user gets logged in, and a valid AccessToken is returned. 

Right now, the code looks like this:
```
@api_view(['POST'])
def register(request):
    qp = RegisterUserSerializer(data=request.data)
    if not qp.is_valid():
        return Response(data=qp.errors, status=status.HTTP_400_BAD_REQUEST)

    username = qp['username'].value
    email = qp['email'].value
    password = qp['password'].value

    user = User.objects.create_user(username, email, password)

    auth_app_name = settings.AUTH_APPLICATION_NAME
    app = Application.objects.get(name=auth_app_name)
    token = AccessToken.objects.get_or_create(user=user, expires=now() + timedelta(days=1), application=app)

    return Response({'token': token.key}, status=status.HTTP_201_CREATED)
```

My issue is that I am having trouble generating the AccessToken. With the code I have now, it seems that the AccessToken is created, but that the token itself is empty. Do you have any suggestion on what might be the correct way to do this?

**Comment by PhilipGarnero** [comment]
You're just missing the token field.
It does not fill itself automatically.
```
from oauthlib.common import generate_token
AccessToken.objects.create(user=user, application=app, token=generate_token(), expires=timezone.now() + timedelta(days=1))
```

**Comment by andrroy** [comment]
Dude, you are amazing! Thank you so much!
