### ISSUE TITLE
Getting error on user field while adding application in admin interface.

### ISSUE THREAD

**Issue by puneetagg** [PhilipGarnero/django-rest-framework-social-oauth2#52]
I am specifying email address(username_field) in a user field while adding application in admin interface.
Error: Select a valid choice. That choice is not one of the available choices.

**Comment by PhilipGarnero** [comment]
When specifying the user for your own application, specify the super user.

**Comment by basiljose1** [comment]
i was unable to choose super user,
Select a valid choice. That choice is not one of the available choices.

**Comment by basiljose1** [comment]
worked charm, in username filed ,just placed super_user id, :+1:
