### ISSUE TITLE
How to retrieve an user in my app by the facebook <user_acess_token>? [help wanted]

### ISSUE THREAD

**Issue by JoabMendes** [PhilipGarnero/django-rest-framework-social-oauth2#55]
I read the documentation did the settings (including the facebook settings as I wish) and the last example is the following command:

```sh
curl -X POST -d "grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=facebook&token=<facebook_token>" http://localhost:8000/auth/convert-token
```
When I execute this, it does the following thing on my app:

1. Creates an user on my app with the same information I want from facebook.
2. It returns the following information:
```json
{"access_token":"XfMZFv7k8qBsUjIwNIM5xUcsgN2zew","token_type":"Bearer","expires_in":36000,"refresh_token":"LLyQzN7kpk7RC8Zr3oK9VeEQlE3S0r","scope":"read write"}
``` 
This seems to be the right behaviour.
However, I want to know how do I retrieve from my system this same user that was created by the last command. Should I make `access_token` an attribute of my user model and search for it using the returned access_token?

**Comment by PhilipGarnero** [comment]
Save your access token somewhere on your client app.
Then, use it to authenticate your requests. The user will automatically be accessible in request.user in your views provided you use the authentication classes.

Feel free to close this when you don't have anymore questions.

**Comment by JoabMendes** [comment]
Thanks @PhilipGarnero , can you give an example of how can I  authenticate my requests (for a example view)? Like a workflow of how I should do it. I am completely new to the django rest framework, also to your package.

**Comment by PhilipGarnero** [comment]
For your api views (views that you manage with rest framework), you can define authentication classes.
You can either define the default authentication classes in your settings.py or per view.
Simply define these two backends `'oauth2_provider.ext.rest_framework.OAuth2Authentication'` `'rest_framework_social_oauth2.authentication.SocialAuthentication'` and then you're all set to authenticate your users.

Simply add a Authorization header and set it to `Bearer <access_token>`. Your user will be available in request.user

**Comment by JoabMendes** [comment]
Understood, I tested as use say and it working. Thank you @PhilipGarnero :+1:
