### ISSUE TITLE
unsupported_grant_type

### ISSUE THREAD

**Issue by rodolphopivetta** [PhilipGarnero/django-rest-framework-social-oauth2#56]
I'm trying to authenticate an user following the instructions in the README, but when I request a token for an user, I receive:
```json
{"error": "unsupported_grant_type"}
```
In my application the "Authorization grant type" field is "password" value:
```python
In [1]: from oauth2_provider.models import Application

In [2]: a = Application.objects.get(id=1)

In [11]: a.authorization_grant_type
Out[11]: u'password'
```

What I'm doing wrong?

**Comment by PhilipGarnero** [comment]
Show me your request so I can help you out

**Comment by rodolphopivetta** [comment]
using the URL
```
http://127.0.0.1:8000/auth/token/
```
method: POST

Body:
```json
{
    "grant_type": "password",
    "client_id": "SxOKjAuWdHDw07NIyogYhjOTn6amDVXSG9WjYydn",
    "client_secret": "ejvOxEmloOobtB45USCljfASygtXxpOUbQiWxJwE60RLA7rhTSmWNLi3YonCTj5orKq8JDxyiKa66QP5mAoiu8mu57qJeCPmXv689P3PoSeJcb7Va30wI8dyJjSrazMR",
    "username": "testuser",
    "password": 123
}
```

**Comment by PhilipGarnero** [comment]
You are sending an integer instead of a string for the password.

**Comment by rodolphopivetta** [comment]
Same error as string
```json
{
    "grant_type": "password",
    "client_id": "SxOKjAuWdHDw07NIyogYhjOTn6amDVXSG9WjYydn",
    "client_secret": "ejvOxEmloOobtB45USCljfASygtXxpOUbQiWxJwE60RLA7rhTSmWNLi3YonCTj5orKq8JDxyiKa66QP5mAoiu8mu57qJeCPmXv689P3PoSeJcb7Va30wI8dyJjSrazMR",
    "username": "testuser",
    "password": "123"
}
```

**Comment by rodolphopivetta** [comment]
```python
In [1]: from oauth2_provider.models import Application

In [2]: a = Application.objects.get(id=1)

In [3]: a.client_id
Out[3]: u'SxOKjAuWdHDw07NIyogYhjOTn6amDVXSG9WjYydn'

In [4]: a.client_secret
Out[4]: u'ejvOxEmloOobtB45USCljfASygtXxpOUbQiWxJwE60RLA7rhTSmWNLi3YonCTj5orKq8JDxyiKa66QP5mAoiu8mu57qJeCPmXv689P3PoSeJcb7Va30wI8dyJjSrazMR'

In [5]: a.client_type
Out[5]: u'confidential'

In [6]: a.authorization_grant_type
Out[6]: u'password'

In [7]: from users.models import CommonUser

In [8]: c = CommonUser.objects.all().first()

In [9]: c.set_password("123")

In [10]: c.username
Out[10]: u'roger_freeman'

In [11]: c.save()
```

In postman:

URL: http://127.0.0.1:8000/auth/token/

Method: POST
```json
{
    "client_id": "SxOKjAuWdHDw07NIyogYhjOTn6amDVXSG9WjYydn",
    "client_secret": "ejvOxEmloOobtB45USCljfASygtXxpOUbQiWxJwE60RLA7rhTSmWNLi3YonCTj5orKq8JDxyiKa66QP5mAoiu8mu57qJeCPmXv689P3PoSeJcb7Va30wI8dyJjSrazMR",
    "username": "roger_freeman",
    "password": "123",
    "grant_type": "password"
}
```

Response:
```json
{
  "error": "unsupported_grant_type"
}
```

**Comment by PhilipGarnero** [comment]
Is your Application object set to confidential ?

**Comment by rodolphopivetta** [comment]
Yes, you can see this in the iPython query above

**Comment by rodolphopivetta** [comment]
```python
In [1]: from oauth2_provider.models import Application

In [2]: a = Application.objects.get(id=1)

In [5]: a.client_type
Out[5]: u'confidential'
```

:smile:

**Comment by rodolphopivetta** [comment]
I discovered the problem, I'm sending requests with ```Content-Type: application/json```, but apparently the required is ```Content-Type: application/x-www-form-urlencoded```

Why is required x-www-form-urlencoded and not json?

And I suggest you add this requirement in the README :smile:

**Comment by PhilipGarnero** [comment]
I had no idea.
It's probably coming from the oauth toolkit package.

**Comment by rodolphopivetta** [comment]
I finally resolve my problem adding this in the settings:
```python
OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}
```

Thanks for your attention @PhilipGarnero and consider adding this information in the instructions

**Comment by jaroslawziolkowski** [comment]
I have same problem, my response is 

```
{
  "error": "unsupported_grant_type"
}
```

after call to

`curl -X POST -d "client_id=webapp&client_secret=mysecrtet&grand_type=password&username=example@example.com&password=passwd" http://localhost/auth/token`

in my oauth2_provider_application table is

<img width="737" alt="zrzut ekranu 2016-05-28 o 21 36 00" src="https://cloud.githubusercontent.com/assets/6404533/15629569/4ea5bb68-251c-11e6-9419-3f84cc474fe9.png">

Doeas someone have idea why?

**Comment by earmc** [comment]
good night everbody. I whould like know if someone have problem with made refresh token. I have this answer "unsupported_grant_type" but when i try to post request a refresh token.   I appreciate if someone can suggest me some solution

this is my body request:

 RequestBody requestBody = new FormEncodingBuilder()

                .add("client_id","confidencial")
                .add("client_secret","confidencial")
                .add("grant_type", "refresh_token")
                .add("refresh_token", tokenRefreshData)
                .add("Content-Type", "application/x-www-form-urlencoded")
                .build();

**Comment by Yungbubu** [comment]
@earmc I have the same problem. Did you figure it out ? If yes, how ? Thanks!

**Comment by hustzoujia** [comment]
@rodolphopivetta   thanks for your right answer. :)
