### ISSUE TITLE
How can I register with an email and password with the API?

### ISSUE THREAD

**Issue by stringsonfire** [PhilipGarnero/django-rest-framework-social-oauth2#59]
Python-social-auth supports this via it's 'EmailAuth' backend, but I can't see how using django-rest-framework-social-oauth2 let's me do that with the API.

What have I missed?

**Comment by PhilipGarnero** [comment]
From the top of my head, it should work without modifying anything if your username field is set to be the email.

**Comment by serranoarevalo** [comment]
Did you ever find a solution for this? If so, how did you do it?
