### ISSUE TITLE
Google Oauth2

### ISSUE THREAD

**Issue by derektoub** [PhilipGarnero/django-rest-framework-social-oauth2#61]
Have you ever used this with Google's Oauth2?

I followed your example to convert a facebook token, and it worked perfectly. However, when I try to use google-oauth2 as the backend, I always get this message:

```
{  
   "error_description":"Backend responded with HTTP403: { "error":{  
      "errors":[  
         {  
            "domain":"usageLimits",
            "reason":"dailyLimitExceededUnreg",
            "message":"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
            "extendedHelp":"https://code.google.com/apis/console"
         }
      ],
      "code":403,
      "message":"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
   }
}.",
"error":"invalid_request"
}
```

**From my settings.py:**

```
AUTHENTICATION_BACKENDS = (
    # Facebook OAuth2
    'social.backends.facebook.FacebookAppOAuth2',
    'social.backends.facebook.FacebookOAuth2',

    # Google OAuth2
    'social.backends.google.GoogleOAuth2',

    # django-rest-framework-social-oauth2
    'rest_framework_social_oauth2.backends.DjangoOAuth2',

    # django
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '***'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '***'
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email',]
```

My request looks like this:

```
curl -v -X POST -d "grant_type=convert_token&client_id=<client_id_here>&client_secret=<client_secret_here>&backend=google-oauth2&token=<google_token_here>" http://localhost:8000/auth/convert-token
```

Have you seen anything like this?

**Comment by PhilipGarnero** [comment]
I never tried the google backend. I know there are some [differences when you're using twitter](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/issues/15) for example so it might require some tweaking.
Could you post here the request that your django server is making to google services ?

**Comment by derektoub** [comment]
Is there an easy way of printing the request? It look like it gets created based on ```grant_types``` from ```TokenEndpoint``` in ```oauthlib.oauth2.rfc6749.endpoints.token``` (all this happens in the ```create_token_response``` method in *django-rest-framework-social-oauth2/build/lib/rest_framework_social_oauth2/oauth2_endpoints.py*)

**Comment by rodolphopivetta** [comment]
I'm having the same problem here

**Comment by derektoub** [comment]
Issue solved.

I was using the wrong google token from my sign-in on iOS. I originally used ``user.authentication.idToken``` which is wrong, and will not work.

The correct token is ```user.authentication.accessToken```.

Onto bigger and better things. You guys rock and this package is great.

(celebration music)[https://www.youtube.com/watch?v=M3fkZeWsyvo]

**Comment by rodolphopivetta** [comment]
Thanks, I discovered that too.

**Comment by godd9170** [comment]
The google client id looks more like a url e.g. `178124116-u7u7fasdjhfhjadsf2siteomikh7hl6e.apps.googleusercontent.com` 

Do you provide that entire string as the `client_id` in the `convert_tokens` request? I'm receiving the error ```{"error_description":"Invalid client_id parameter value.","error":"invalid_request"}```
when I try it.

**Comment by PhilipGarnero** [comment]
The client_id should be the one generated by the application model you created.

**Comment by godd9170** [comment]
@PhilipGarnero ah yes, that's definitely it. Thanks for getting back.

**Comment by menecio** [comment]
@godd9170 wait, client_id is not the one given by google when you generate your credential? Then what?

**Comment by shayan72** [comment]
> The client_id should be the one generated by the application model you created.

By `client_id generated by the application model` you mean `SOCIAL_AUTH_GOOGLE_OAUTH2_KEY `?

**Comment by sumit-neo** [comment]
> > The client_id should be the one generated by the application model you created.
> 
> @PhilipGarnero By "client_id generated by the application model" you mean `SOCIAL_AUTH_GOOGLE_OAUTH2_KEY `?
> 
> It does not work for me and I still get `{"error_description":"Invalid client_id parameter value.","error":"invalid_request"}`

@PhilipGarnero : Client Id is that you have generated in django admin by creating application

**Comment by a-braham** [comment]
On another issue, how are you guys doing tests for this?

**Comment by ernesto-handy** [comment]
Facebook works well for me but with Google I am getting http error 400, I am sending this in the POST from my Android to auth/convert-token/:
```
"grant_type" -> "convert_token"
"backend" -> "google-oauth2"
"client_id" -> "My client id generated by Django admin"
"token" -> "The token generated by google sign in"
```

And I have this on my settings on backend:
```
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    .....
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "The client id I got from Google Api Keys in form of 8057483621490-8idklcos9uaow8kvdlks7ue92m8n7v3rss6.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "The secret key in that same page"
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email']
```

**Comment by EzeGimenez** [comment]
> Facebook works well for me but with Google I am getting http error 400, I am sending this in the POST from my Android to auth/convert-token/:
> 
> ```
> "grant_type" -> "convert_token"
> "backend" -> "google-oauth2"
> "client_id" -> "My client id generated by Django admin"
> "token" -> "The token generated by google sign in"
> ```
> 
> And I have this on my settings on backend:
> 
> ```
> AUTHENTICATION_BACKENDS = (
>     # Google OAuth2
>     'social_core.backends.google.GoogleOAuth2',
> 
>     # Facebook OAuth2
>     'social_core.backends.facebook.FacebookAppOAuth2',
>     'social_core.backends.facebook.FacebookOAuth2',
> 
>     # django-rest-framework-social-oauth2
>     'rest_framework_social_oauth2.backends.DjangoOAuth2',
>     'django.contrib.auth.backends.ModelBackend',
> )
> 
> SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "The client id I got from Google Api Keys in form of 8057483621490-8idklcos9uaow8kvdlks7ue92m8n7v3rss6.apps.googleusercontent.com"
> SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "The secret key in that same page"
> SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email']
> ```

Did you manage to fix it? Having the same issue

**Comment by mayankwadhwani** [comment]
@EzeGimenez && @ernesto-handy were you guys able to find a fix?

**Comment by EzeGimenez** [comment]
> @EzeGimenez && @ernesto-handy were you guys able to find a fix?

Ended up making my own tokenid verifier and basic account info retriever with google-oauth2. If you want to make it this way, just ask😁

**Comment by mayankwadhwani** [comment]
@EzeGimenez would be glad if you can share

**Comment by mayankwadhwani** [comment]
> > @EzeGimenez && @ernesto-handy were you guys able to find a fix?
> 
> Ended up making my own tokenid verifier and basic account info retriever with google-oauth2. If you want to make it this way, just askgrin

Is there a existing repo, refering to which i can do the same?
