### ISSUE TITLE
404 on http://localhost:8000/auth/convert-token

### ISSUE THREAD

**Issue by ajay2611** [PhilipGarnero/django-rest-framework-social-oauth2#63]
Hi,

I used same settings as 
https://github.com/PhilipGarnero/django-rest-framework-social-oauth2#facebook-example but whenever I try to 
curl -X POST -d "grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=facebook&token=<facebook_token>" http://localhost:8000/auth/convert-token
I get a 404 response
Is there anything that I need to add in my <app>.urls file?
Please help.

**Comment by PhilipGarnero** [comment]
Did you add `url(r'^auth/', include('rest_framework_social_oauth2.urls')),` in your root url conf ?

**Comment by ajay2611** [comment]
Thanks for that. I just added settings from fb part. Now, I've fixed this and trying 
curl -X POST -d "grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=facebook&token=<facebook_token>" http://localhost:8000/auth/convert-token

where client_id, client_secret & facebook_token are replaced by actual values but I'm getting 
{"error":"invalid_request","error_description":"Invalid client_id parameter value."}

**Comment by PhilipGarnero** [comment]
I suggest you read the readme one more time. If you missed the url part you probably skimmed through it but it is important to read id thoroughly. Everything is explained. Come back here if you still can't figure it out after that.
