### ISSUE TITLE
{"error_description":"Invalid client_id parameter value.","error":"invalid_request"}

### ISSUE THREAD

**Issue by ajay2611** [PhilipGarnero/django-rest-framework-social-oauth2#64]
Hi PhilipGarnero,

I've thoroughly read docs this time, but still 
 curl -X POST -d "grant_type=convert_token&client_id=147**********719&client_secret=b064*******************************263>&backend=facebook&token=<facebook_token>" http://localhost:8000/auth/convert-token

where 
cliend_id is my fb app-id
cliend_secret is app-secret
facebook-token is user-token I got from https://developers.facebook.com/tools/accesstoken/
EAAU****************************************************************************************ZDZD

Error I'm getting is: 
{"error_description":"Invalid client_id parameter value.","error":"invalid_request"}

Please help.

**Comment by PhilipGarnero** [comment]
The client id and client secret shouldn't be your facebook app id and secret.
These should simply go into the settings.py.
Normally, you created an application inside the django admin.
This is where you find the client_id and client_secret.

**Comment by ajay2611** [comment]
Thanks PhilipGarnero. Got it working this time.

**Comment by kunal097** [comment]
@PhilipGarnero Can you help me to find client id and client secret. I'm get confused.

**Comment by ajay2611** [comment]
I don't remember the exact names but open your admin panel, create a new object corresponding to facebook. That will return a client ID and secret to be used in APIs.

**Comment by kunal097** [comment]
@ajay2611 Thank you, it helped me alot.

**Comment by abubakarA-Dot** [comment]
> The client id and client secret shouldn't be your facebook app id and secret.
> These should simply go into the settings.py.
> Normally, you created an application inside the django admin.
> This is where you find the client_id and client_secret.

I have also got the same issue after 2 years. I did the same way you described but still getting the same error which ajay got.
