### ISSUE TITLE
facebook login username

### ISSUE THREAD

**Issue by derektoub** [PhilipGarnero/django-rest-framework-social-oauth2#66]
How is the django username determined when you create a new user through the following process:
1. do facebook login
2. trade the facebook token for a native token

**Comment by PhilipGarnero** [comment]
See [this line](https://github.com/omab/python-social-auth/blob/master/social/backends/facebook.py#L39) in python-social-auth's facebook backend.

It tries to get an `username` attribute directly from the facebook api and falls back on a `name` attribute.
