### ISSUE TITLE
Interrupt pipeline when registering from social network

### ISSUE THREAD

**Issue by mr-const** [PhilipGarnero/django-rest-framework-social-oauth2#67]
Is it possible to interrupt pipeline when registering user from social network, so we can show him `Terms of Service` and force to choose our system's password before `Django User` will be created?

**Comment by johannesreichard** [comment]
You might search for the disconnection pipeline, a feature of python-social-auth http://psa.matiasaguirre.net/docs/pipeline.html#disconnection-pipeline

**Comment by jd-0001** [comment]
@johannesreichard I have followed the same, But i got 'HttpResponseRedirect' object has no attribute 'is_active'

You can check https://github.com/RealmTeam/django-rest-framework-social-oauth2/issues/208 & [Stackoverflow](https://stackoverflow.com/questions/58991950/python-social-auth-partial-pipeline-redirect-gives-httpresponseredirect-object) for more details. Can you please provider sample repo which pauses pipeline and resume on form submit with drf.
