### ISSUE TITLE
{"error_description":"Invalid client_id parameter value.","error":"invalid_request"}

### ISSUE THREAD

**Issue by nyabwana** [PhilipGarnero/django-rest-framework-social-oauth2#68]
Hello Philip,
I have followed all the steps in the tutorial but I get an error when I get to try converting the token from facebook. It gives me {"error_description":"Invalid client_id parameter value.","error":"invalid_request"}

**Comment by PhilipGarnero** [comment]
Did you create an application object inside the django admin ?

**Comment by nyabwana** [comment]
yes I created one. But I am using a custom user model as per the steps in the official django documentation.

**Comment by PhilipGarnero** [comment]
Is the client_id the one from your application model ?

**Comment by nyabwana** [comment]
No, I used the client_id and client_secret from facebook. Should I use the ones of my application model?

**Comment by PhilipGarnero** [comment]
Yes, the ones from facebook should be put in your settings.py
