### ISSUE TITLE
Configurable url namespace

### ISSUE THREAD

**Issue by maryokhin** [PhilipGarnero/django-rest-framework-social-oauth2#69]
Hi, I went through the tutorial and got everything to work nicely. 

The only thing I'm missing in terms of functionality, is being able to set the namespace of the urls, similar to https://github.com/omab/python-social-auth/issues/399. This would allow to configure the urls of this package to live on a nested path, i.e. `/v2/auth/`, because currently it's hardcoded to work only on the root path `/auth/`. Is this something you would consider adding?

**Comment by PhilipGarnero** [comment]
Hello,

I'll gladly add the functionality if that's possible.
I'll have to check if python-social-auth and django-oauth-toolkit can be configured by my package first.
I'll do this when I have time.

PRs are welcomed as well.

**Comment by maryokhin** [comment]
Yes, it's quite easy to add, the same as python-social-auth, by having a setting for the app, i.e. `REST_AUTH_URL_NAMESPACE`.

Btw, currently the app has only one setting `PROPRIETARY_BACKEND_NAME `, but it should probably have some kind of prefix system, to avoid clashes in naming with other apps.
