### ISSUE TITLE
Convert token using Implicit Grant Type

### ISSUE THREAD

**Issue by RomelioTavas** [PhilipGarnero/django-rest-framework-social-oauth2#75]
Is there a way to convert tokens without exposing the client secret?

The convert-token route is potentially insecure for JavaScript Apps since JS cannot store client_secret securely. From what I've researched, OAuth applications should use Implicit Grant when dealing with JS Apps. Is there a way to convert tokens with Implicit Grant using this library?

Convert Token Route:
`curl -X POST -d "grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=<backend>&token=<backend_token>" http://localhost:8000/auth/convert-token`

**Comment by PhilipGarnero** [comment]
On your server, create a new application object.
Set the client type as public and the authorization grant type as client credentials.

This will allow you to omit the client secret when converting a token.
