### ISSUE TITLE
From Dec 03 2016, python-social-auth lib is deprecated 

### ISSUE THREAD

**Issue by andrew21c** [PhilipGarnero/django-rest-framework-social-oauth2#77]
the python-social-auth lib is deprecated now.  Could you please update this django-rest-framework-social-oauth2 using social-app-django and social-core libs?

Thanks.
Andy

**Comment by andrew21c** [comment]
I have fixed the python-social-auth lib deprecation problem in my local copy of django-rest-framework-social-oauth2. Still testing it. Not sure if I can upload it or not.

**Comment by palzuncoff** [comment]
Please show me how you fixed, I take error when try migrate 
`ImportError: Could not import 'rest_framework_social_oauth2.authentication.SocialAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name requests.`
