### ISSUE TITLE
Adding a Custom Backed to python-social-auth

### ISSUE THREAD

**Issue by nesh170** [PhilipGarnero/django-rest-framework-social-oauth2#80]
I added a custom backend to python-social-auth for another provider's OAuth. When i try using

```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=duke&token=<token> "http://localhost:8000/auth/convert-token"
```

It returns:-
```
{
  "error": "invalid_request",
  "error_description": "Invalid client_id parameter value."
}
```

I defined the client key and secret in the settings.py

Thanks

**Comment by PhilipGarnero** [comment]
Did you open the django admin to create an Application object ?
The client id and secret asked here are those that belong to the Application object.

**Comment by nesh170** [comment]
Thanks, I added those and I made progress. Currently I get the following error

    return {'details': dict(backend.get_user_details(response), **details)}
  File "C:\Python34\lib\site-packages\social_core\backends\base.py", line 162, in get_user_details
    raise NotImplementedError('Implement in subclass')
NotImplementedError: Implement in subclass
[18/Feb/2017 01:48:54] "POST /auth/convert-token HTTP/1.1" 500 19407

I created my own custom backend (and get_user_details is defined)
DRFSO2_PROPRIETARY_BACKEND_NAME = 'duke'

AUTHENTICATION_BACKENDS = (
    'inventoryProject.dukeAuth.DukeOAuth2',
    'rest_framework_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend'
)

**Comment by PhilipGarnero** [comment]
Show me the code of your backend

**Comment by nesh170** [comment]
Sorry, I manage to fix it by deleting the following 
    'rest_framework_social_oauth2.backends.DjangoOAuth2' from my authentication backend
