### ISSUE TITLE
How to call ConvertTokenView class in my views and url

### ISSUE THREAD

**Issue by mertgunay** [PhilipGarnero/django-rest-framework-social-oauth2#82]
I guess I have to call this method in my own views because I am using mobile application.

So I should not put cliend id and client secret in the application. 

But if I do like this when a person click facebook login button in my app ;
 
http://myip.com/auth/register/facebook?acces_token=<token> I can call the a method in my views and I can put client ID and cliend secret there. 

How can I do this. Please help me

**Comment by PhilipGarnero** [comment]
The goal is to use that view from client applications, mobile included.
To prevent the client_secret from being present in your mobile app, you can create a public Application on the django admin site and only use the client_id.

**Comment by mertgunay** [comment]
But how can I do this, please more information

**Comment by wowkin2** [comment]
Is it secure to use public Applications?

**Comment by PhilipGarnero** [comment]
@wowkin2 It's part of the oauth2 specs [example here](http://tutorials.jenkov.com/oauth2/client-types.html).
@mertgunay Please, read the documentation again. Everything is explained inside.
