### ISSUE TITLE
Multiple accounts (again)

### ISSUE THREAD

**Issue by moonwolf-github** [PhilipGarnero/django-rest-framework-social-oauth2#83]
I'm sorry but i can't figure it out. Lets say i have user with password (it's been created before any social attempts). I can get its token using `curl -X POST -d "client_id=<id>&client_secret=<secret>&grant_type=password&username=user1&password=<pass>" http://localhost:8100/auth/token`. Then i can use this token to get data from server.

Now, suppose i want to attach Google OAuth2 to this user. I was trying like this:
`curl -H "Authorization: Bearer <user1-token>" -X POST -d "grant_type=convert_token&client_id=<id>&client_secret=<secret>&backend=google-oauth2&token=<google_token>" http://localhost:8100/auth/convert-token`

And it doesn't work - i get new user not associated with `user1`. I was trying to extend auth pipeline but i can't get `user1` there. How should i do it?

**Comment by PhilipGarnero** [comment]
This is not related to my package but to python-social-auth.
You should check this [link](http://python-social-auth-docs.readthedocs.io/en/latest/use_cases.html#associate-users-by-email) regarding your issue.

**Comment by moonwolf-github** [comment]
OK, thanks.

**Comment by veddermatic** [comment]
I was able to get around this by adding a step to my pipeline that picked up the `strategy.request.user` to not create new accounts like so:

```
def apiUserPipeline(strategy, details, backend, user=None, *args, **kwargs):
    if  user is None and strategy.request.user:
        return {'user': strategy.request.user}
```

It is odd that `convert_token` does not seem to "see" the authenticated users the same way that using vanilla `social_app_django` does when you hit their `begin` URL.  But using something like the the above early in your pipeline (I have it as the 5th step before the `get_username` part of the default pipeline.
