### ISSUE TITLE
Support for Chrome App OAuth2 convert-token.

### ISSUE THREAD

**Issue by godd9170** [PhilipGarnero/django-rest-framework-social-oauth2#84]
I'm trying to use the `chrome.identity` api to obtain an Access token to then hit `convert-token`. The only way to use `chrome-identity` however, is to register a chrome app as opposed to a standard web application.
![credentials_-_shakespeare-dev](https://cloud.githubusercontent.com/assets/4411118/24384118/9241da26-132f-11e7-83c2-50c90614dd6f.png)

The chrome apps unfortunately don't have a `client_secret` and therefore the endpoint is no good. Is there a way to combat this?

**Comment by PhilipGarnero** [comment]
I'm not familiar with google as a backend but the doc from python-social-auth is [here](https://python-social-auth.readthedocs.io/en/latest/backends/google.html#google-oauth2).
You should take a look at it.

Close this issue if you found the answer.

**Comment by godd9170** [comment]
Thanks for the prompt response @PhilipGarnero, I've created https://github.com/python-social-auth/social-app-django/issues/43 to address it.
