### ISSUE TITLE
About SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS

### ISSUE THREAD

**Issue by murabo** [PhilipGarnero/django-rest-framework-social-oauth2#86]
Facebook's gender information is not registered in the DB.

How can I register?

```python:settings.py
AUTH_USER_MODEL = 'Myapp.User'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, gender'
}
```

```python:models.py
class User(AbstractUser):
    gender = models.CharField(_('gender'), max_length=6, blank=True)
```

**Comment by PhilipGarnero** [comment]
This is not an issue related to this project.
Checkout the docs of [python-social-auth's pipeline](http://python-social-auth-docs.readthedocs.io/en/latest/pipeline.html#extending-the-pipeline) to do what you want.
