### ISSUE TITLE
Verify account

### ISSUE THREAD

**Issue by BojanKogoj** [PhilipGarnero/django-rest-framework-social-oauth2#87]
> If the user was not registered on your app, it will create a new user to be used.

Is it possible to only verify if user has an account? I don't want to create one if he doesn't

**Comment by PhilipGarnero** [comment]
Checkout [this section](http://python-social-auth-docs.readthedocs.io/en/latest/pipeline.html#authentication-pipeline) about the pipeline inside python social auth docs.  
There's an example pipeline that doesn't create users.
