### ISSUE TITLE
Google Auth issue from Android: 'GoogleOpenId' object has no attribute 'do_auth'

### ISSUE THREAD

**Issue by daesu** [PhilipGarnero/django-rest-framework-social-oauth2#91]
Hi all, 

I am trying to use /convert_token after successfully getting an access token from the Google Android SDK GoogleSignInResult

Settings for the athentication backends are;

```
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
```

I am sending the request as follows;

```
{
 "grant_type": "convert_token",  
  "client_id": "snip",
  "client_secret": "snip",
  "backend": "google",
 "token": "snip"
}
```

And the result is;

`AttributeError: 'GoogleOpenId' object has no attribute 'do_auth'`

Has anyone successfully implemented the flow for this from android ? Also I'm a bit confused regarding the authentication backends. Setting the backend to 'google', how does it decide which Google backend to use ? (Oauth2 vs OpenID etc) ?

Thanks in advance.

**Comment by PhilipGarnero** [comment]
I've never tried using openid connect so I can't help you with that.
However, google-oauth2 should work as a backend, see [this old issue](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/issues/61) for more insights.

Reopen if you can't make it work.

**Comment by daesu** [comment]
Hi Philip, 

It seems Google no longer allows/recommends to get the access token and instead suggest to use an 'id token'. https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint

On Android at least the methods to retrieve an access token have been deprecated.

It seems that the suggested method is to send the ID token to the backend and the backend proceeds with that.

**Comment by PhilipGarnero** [comment]
Yes, I'm well aware of that. You can still use the deprecated method for now. It's not unsafe (a lot of oauth2 services work like that) and you'll be able to switch to the recommended method as soon as I'm finished with issue #72

**Comment by trananhkma** [comment]
Hi daesu,
Do you have any solution for this?
I still got the same problem as you.
Can I use other way to force django-rest-framework create token after verifing the id_token?

**Comment by daesu** [comment]
Hi @trananhkma no sorry I have no solution. We ended up not using google auth at the time due to time constraints and never came back to implement it since.

**Comment by trananhkma** [comment]
Thank you @daesu 
After verfying id_token, I have tried to create a token then save it manualy follow BearerToken way (from oauthlib/oauth2).
This token worked well with django rest framework
