### ISSUE TITLE
Unable to create a new User via password

### ISSUE THREAD

**Issue by Yungbubu** [PhilipGarnero/django-rest-framework-social-oauth2#94]
Hi All,

I'm having trouble creating a new user via password, whereas I have no problem via Facebook auth.

I'm using the 1.0.4 version of the package.

What I am doing:

Send a POST request to "http://localhost:8000/auth/token"

With these parameters (in x-www-form-urlencoded): 

![image](https://cloud.githubusercontent.com/assets/8428699/26677316/b947604e-46cb-11e7-9810-d0682ed09dbf.png)

And I get the following error: 

{
  "error_description": "Invalid credentials given.",
  "error": "invalid_grant"
}

I am missing something ?

Any help will be greatly appreciated!

Regards,

**Comment by PhilipGarnero** [comment]
This library only creates users for social accounts.
You have to implement user registration with passwords on your own.
You can checkout [this example](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/issues/4#issuecomment-108624629) for help.

**Comment by Yungbubu** [comment]
Thanks, It works
