### ISSUE TITLE
Could not import 'oauth2_provider.ext.rest_framework.OAuth2Authentication'

### ISSUE THREAD

**Issue by Revocsid** [PhilipGarnero/django-rest-framework-social-oauth2#96]
Hi, 

I updated my package version to 1.0.6 and I had this following error when I tried to start my django server : 

`ImportError: Could not import 'oauth2_provider.ext.rest_framework.OAuth2Authentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: No module named ext.rest_framework.`

This is the concerned part of my settings file : 

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
}
```
Does anybody know what is going on ? I have the same config file as the tutorial

**Comment by PhilipGarnero** [comment]
Apparently, django-oauth-toolkit [did an update](https://github.com/evonove/django-oauth-toolkit/commit/cdc00603e738fdf78a217754196113cadc000f4f).
Change `oauth2_provider.ext.rest_framework.OAuth2Authentication` to `oauth2_provider.contrib.rest_framework.OAuth2Authentication` for now.
I'll release an updated version later.

**Comment by Revocsid** [comment]
Thanks for your reply
`auth2_provider.contrib.rest_framework.OAuth2Authentication` did the trick for the config part

But it seems that there is some other related imports in the package, right now I have this following error  : 
```
File "/env/lib/python2.7/site-packages/rest_framework_social_oauth2/views.py", line 7, in <module>
    from oauth2_provider.ext.rest_framework import OAuth2Authentication
ImportError: No module named ext.rest_framework
```

**Comment by PhilipGarnero** [comment]
Yes, I noticed the issue a bit after.
Update to 1.0.7 and you should be fine.
